### ISSUE TITLE
Custom Script Error in new sales order

### ISSUE THREAD

**Issue by cgpurbaugh** [cgpurbaugh/metalcraft#1]
eval code
eval@[native code]
setup@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:60045
setup@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:13119
refresh@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:19037
load@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:11607
https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:11330
https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:115071
initializePromise@[native code]
Promise@[native code]
with_doc@https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:114824
show_doc@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:11263
https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:10611
with_doctype@https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:114496
make@https://sea-fire.agritheory.com/assets/js/form.min.js?ver=1553530253.0:1:10476
show@https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:292497
route@https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:62966
https://sea-fire.agritheory.com/assets/js/desk.min.js?ver=1553530253.0:1:65095
dispatch@https://sea-fire.agritheory.com/assets/frappe/js/lib/jquery/jquery.min.js:3:7542
handle@https://sea-fire.agritheory.com/assets/frappe/js/lib/jquery/jquery.min.js:3:5625

**Comment by agritheory** [comment]
@cgpurbaugh What doctype is this custom script associated with?
Edit: Mentioned in the title.

**Comment by agritheory** [comment]
@cgpurbaugh Errors are resolved. V11 wants javascript to be mostly in strict mode, so all variables have to be defined with `var` (global-ish/ page scope) or `let` (function/class scope).
