### ISSUE TITLE
Non-Stock items are requiring batch

### ISSUE THREAD

**Issue by cgpurbaugh** [cgpurbaugh/metalcraft#20]

**Comment by cgpurbaugh** [comment]
May have resolved itself

**Comment by cgpurbaugh** [comment]
This issue reappeared Friday with the 140-000 PN.

**Comment by agritheory** [comment]
@cgpurbaugh Chris I think you said you were able to fix this one via bulk update?

**Comment by cgpurbaugh** [comment]
@agritheory Yes.
